# 网站标题
title: "kewen的主页"

# 网站邮箱/描述
email: your-email@example.com
description: >-
  这是我的个人学术主页，分享我的研究、项目和心得。

# 基本设置
baseurl: "" # 如果你的网站不在根目录，比如在 /blog，则这里填 "/blog"。对于 [用户名].github.io 这种，保持为空即可。
url: "https://your-username.github.io" # 用你的实际用户名替换 "your-username"

# 构建设置
theme: minima # 这是 GitHub Pages 默认的轻量级主题

# 网站导航栏链接
navbar-links:
  关于我: "/about"
  博客: "/blog"
  出版物: "/publications"
  项目: "/projects"
